server:
  port: 8080
mysql:
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  database: research_sys
  charset: utf8mb4
  parseTime: True
  loc: Local
mongodb:
  username: admin
  password: 123456
  host: 127.0.0.1
  port: 27017
  authSource: admin
redis:
  password: 123456
  host: 127.0.0.1
  port: 6379