server:
  port: 8080
jwt-secret: FU&3$#gy5ZAZ5rgQ5g8MT3SD&M63%YwY
mysql:
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  database: research_sys
  charset: utf8mb4
  parseTime: True
  loc: Local
  max-open-size: 50 #连接池最大连接数
  max-idle-size: 10 #连接池最大空闲数
redis:
  password: 123456
  host: 127.0.0.1
  port: 6379
