definitions:
  req.RoleCreateReq:
    properties:
      desc:
        type: string
      permissions:
        items:
          type: integer
        type: array
      title:
        type: string
    type: object
  req.RoleUpdateReq:
    properties:
      desc:
        type: string
      permissions:
        items:
          type: integer
        type: array
      title:
        type: string
    type: object
  res.Result:
    properties:
      code:
        example: 200
        type: integer
      data:
        type: object
      message:
        example: 响应信息
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: An example of gin
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Research sys API
  version: "1.0"
paths:
  /api/role:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功后返回值
          schema:
            $ref: '#/definitions/res.Result'
      security:
      - ApiKeyAuth: []
      summary: list role
    post:
      consumes:
      - application/json
      parameters:
      - description: 角色信息
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/req.RoleCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功后返回值
          schema:
            $ref: '#/definitions/res.Result'
      security:
      - ApiKeyAuth: []
      summary: create role
  /api/role/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功后返回值
          schema:
            $ref: '#/definitions/res.Result'
      security:
      - ApiKeyAuth: []
      summary: destroy role
    get:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功后返回值
          schema:
            $ref: '#/definitions/res.Result'
      security:
      - ApiKeyAuth: []
      summary: retrieve role
    put:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: 角色信息
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/req.RoleUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功后返回值
          schema:
            $ref: '#/definitions/res.Result'
      security:
      - ApiKeyAuth: []
      summary: update role
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
